### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/bam_scanner.rs:234:41

### ISSUE THREAD

**Issue by linlin-coder** [PacificBiosciences/HiFiCNV#11]
tool version:0.1.6
command example:
```shell
hificnv-v0.1.6-x86_64-unknown-linux-gnu/hificnv \
 --bam sample1.sort.bam \
 --ref Homo_sapiens_assembly38.onlychr.fasta \
 --exclude hificnv-v0.1.5-x86_64-unknown-linux-gnu/data/excluded_regions/cnv.excluded_regions.common_50.hg38.bed.gz \
 --threads 20 \
 --output-prefix CallCNV_hificnv-v0.1.6
```
problem description: 
When I run a command, an error always occurs, `thread '<unnamed>' panicked at 'called' Option:: unwrap() ` on a 'None' value ', src/bam_ scanner.rs:234:41`  
![image](https://github.com/PacificBiosciences/HiFiCNV/assets/77706356/b8396c44-47ce-4bf7-b1b2-50c5be4fad47)

**Comment by linlin-coder** [comment]
The software version v0.1.5 can run, but the results do not match my expectations. Please refer to the issue for details #12

**Comment by holtjma** [comment]
Couple notes from this:

- It looks like we accidentally uploaded an incorrect version of the v0.1.6 binary, I've modified the release (https://github.com/PacificBiosciences/HiFiCNV/releases/tag/v0.1.6) to have the correct version.  The old one is preserved with the `deprecated-` prefix.
- This error should only occur if there is a mismatch between the BAM file chromosome and the reference genome chromosomes.  If you use the new version of the binary, it should clarify which chromosomes are absent in the reference.

Sorry about the incorrect upload!

**Comment by linlin-coder** [comment]
Hello developer, thank you for your answer to this question and for fixing this anomaly. I have tested the new version of the software ,and the software can output chromosome information for differences between Fasta and Bam files. Thank you again for your help
