### ISSUE TITLE
Joint variant calling

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/HiFiCNV#13]
Hello,

Can we do joint variant calling of samples in HiFiCNV?

Thank you

**Comment by ctsa** [comment]
Thanks @priyambial123, There is no joint calling at the moment. Can you tell us more about your use case?

**Comment by priyambial123** [comment]
I am looking for shared rare structural variants in affected family members of bipolar disorder. I have been using pbsv tool for joint variant calling

Thank you

**Comment by ctsa** [comment]
Thanks, that is helpful to understand.

The longer term thinking on joint sample analysis is to support some combination of targeted SV testing (increase sensitivity on a recurrent SV at cohort scale) and perhaps a true joint analysis at family-scale (meaning something like >= 10 samples).

Neither of these options are likely to be coming short term, so I think you would need to combine single sample runs and merge if using HiFiCNV today.

**Comment by ctsa** [comment]
Closing as answered.
