### ISSUE TITLE
Deepvariant file for minor allele frequency calculation

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/HiFiCNV#15]
Hello,

I have a question in the example run. Why deepvariant file which has SNPs and indels is used as an input file. How the information from this file can be used to find the minor allele frequency of CNVs?. Can you explain this

Thank you

**Comment by ctsa** [comment]
The small variant allele frequency can be used to help call or visually validate the CNV calls. It's entirely optional for HiFiCNV, if you include it you'll get the maf bigwig track in the output, which can be used in IGV.

**Comment by ctsa** [comment]
Closing as answered
