### ISSUE TITLE
Genotype 1/1

### ISSUE THREAD

**Issue by NannapatS** [PacificBiosciences/HiFiCNV#17]
Does HiFiCNV can produce genotype​ 1/1 for hemizygous of chromosome X or Homozygous?  I saw only 0/1 on my result. Thanks in advance​ for your help.

**Comment by ctsa** [comment]
Thanks @NannapatS, the strategy for assigning genotypes to copy number changes in HiFiCNV is still being worked out. The method currently outputs `0/1` for all cases. The copy number itself (`FORMAT::CN`) is currently the primary call type. Could this work for you or do you have a use case relying on GT?

**Comment by NannapatS** [comment]
Dear Chris,

I trust this message finds you well. Your swift response is greatly appreciated. Allow me to introduce myself as a PhD candidate working in collaboration with Professor Vorasuk at the Excellence Center for Genomics and Precision Medicine, located within Chulalongkorn University in Thailand.

At present, our research endeavors revolve around the intricate realm of trio analysis, where our focus lies in elucidating the modes of inheritance such as De novo mutations, Autosomal Recessive scenarios both in Homozygous and Compound Heterozygous contexts, as well as the X-linked Recessive pattern. To accomplish this, we have harnessed the power of Pacbio HiFi sequencing, meticulously conducted using the Sequel IIe system. It's worth noting that our tool of choice for the subsequent analysis is the HiFiCNV software, a recommendation stemming from the experts at Pacbio.

In the midst of these intricacies, I wish to emphasize the pivotal role that the Genotype (GT) information plays in our CNV (Copy Number Variation) analysis. This key data component holds immense significance and directly influences the accuracy and depth of our investigations.

Given the pressing nature of our research and its implications, I kindly request your assistance in expediting the accommodation of this specific requirement. Your prompt support in this regard would undoubtedly contribute significantly to the progress of our research endeavors.

Thank you for your time, understanding, and your consideration of our request. Looking forward to the positive impact that your collaboration could bring to our work.

Warm regards,

[https://sgh.md.chula.ac.th/wp-content/uploads/2021/08/3-5.png]<https://sgh.md.chula.ac.th/research/4308/>
Excellence Center for Genomics and Precision Medicine - School of Global Health, Faculty of Medicine, Chulalongkorn University<https://sgh.md.chula.ac.th/research/4308/>
Genomics and Precision Medicine for public well-being The Excellence Center for Genomics and Precision Medicine was developed from the Excellence Center of Medicine Genetics due to the rapid advances and continuing growth of knowledge in Genetics and Genomics over the past decades. The next-generation sequencing (NGS) technology which includes whole exome sequencing and whole genome
sgh.md.chula.ac.th




นันท์นภัส เศรษฐวิศวสกุล
Nannapat Settavisavasakul

Ph.D. Candidate
Bioinformatics and Computational Biology, Chulalongkorn University
M.A. (Economics)
B.Eng (Computer Engineering)

Agile Project Management Practitioner Certificate
IT Service Management - ITIL Certificate
Lean Six Sigma Black Belt Certificate
Learning Distant MBA Certificate


________________________________

**Comment by ctsa** [comment]
I created an enhancement ticket (#19) to cover the topic.

**Comment by NannapatS** [comment]
Dear all
Could you please help to confirm me? Have this feature already been implemented ? Thanks in advance for your cooperation.


นันท์นภัส เศรษฐวิศวสกุล
Nannapat Settavisavasakul

Ph.D. Candidate
Bioinformatics and Computational Biology, Chulalongkorn University
M.A. (Economics)
B.Eng (Computer Engineering)

Agile Project Management Practitioner Certificate
IT Service Management - ITIL Certificate
Lean Six Sigma Black Belt Certificate
Learning Distant MBA Certificate


________________________________

**Comment by holtjma** [comment]
@NannapatS This potential feature or change is being tracked in #19.
