### ISSUE TITLE
Error in BAM Scanner: 'unwrap!

### ISSUE THREAD

**Issue by mugglejolin** [PacificBiosciences/HiFiCNV#23]
Hi,

I have already included '--cov-regex "."' in the command line, but I still received the following error message:
thread '<unnamed>' panicked at '
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   unwrap! called on Option::None                                             !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
src/bam_scanner.rs:234,41 in hificnv::bam_scanner
Chromosome "1" detected in BAM file, but not in the reference file
', /var/lib/bamboo/.cargo/registry/src/github.com-1ecc6299db9ec823/unwrap-1.2.1/src/lib.rs:93:25

Note: Please run the command with 'RUST_BACKTRACE=1' environment variable to display a backtrace.

I'm not sure why this error is occurring despite including the --cov-regex option. Any insights or suggestions would be greatly appreciated!

**Comment by holtjma** [comment]
Hi @mugglejolin,

This is the new error message that appears when there is a mismatch between the BAM and the reference file provided on the CLI (see https://github.com/PacificBiosciences/HiFiCNV/issues/11). This likely means that BAM file you're was aligned to a different reference file than the one you provided to HiFiCNV.

Matt

**Comment by mugglejolin** [comment]
Thanks! It is working now since I regenerated the aligned BAM file from scratch to ensure consistency.

**Comment by ctsa** [comment]
Thanks for reporting this @mugglejolin, we can change the error message in future updates to clarify this is an input file compatibility issue without all of the panic/unwrap messaging.
