### ISSUE TITLE
ERROR: "Diploid chromosome regex '.' does not match any sample chromosome names..."

### ISSUE THREAD

**Issue by seetarajpara** [PacificBiosciences/HiFiCNV#24]
I set up my test run like this:

```
REF='~/pacbio/refs/human_GRCh38_no_alt_analysis_set.tar.2023-12-04.gz' \
EXCLUDE='~/pacbio/refs/cnv.excluded_regions.common_50.hg38.bed.gz' \
EXPECTED_CN='~/pacbio/refs/expected_cn.hg38.XY.bed'

hificnv \
    --bam m84039_231121_213913_s2.hifi_reads.bam \
    --ref ${REF} \
    --exclude ${EXCLUDE} \
    --expected-cn ${EXPECTED_CN} \
    --threads 16 \
    --output-prefix hificnv \
    --cov-regex "."
```

and I keep getting this error:

```
[2024-03-04][14:33:15][hificnv][INFO] Starting hificnv
[2024-03-04][14:33:15][hificnv][INFO] cmdline: hificnv --bam m84039_231121_213913_s2.hifi_reads.bam --ref /scratch1/seetaraj/pacbio/refs/human_GRCh38_no_alt_analysis_set.tar.2023-12-04.gz --exclude /scratch1/seetaraj/pacbio/refs/cnv.excluded_regions.common_50.hg38.bed.gz --expected-cn /scratch1/seetaraj/pacbio/refs/expected_cn.hg38.XY.bed --threads 8 --output-prefix hificnv --cov-regex .
[2024-03-04][14:33:15][hificnv][INFO] Running on 8 threads
thread 'main' panicked at 'Diploid chromosome regex '.' does not match any sample chromosome names, use '--cov-regex "."' to match all available chromosomes.', src/cli.rs:234:5
```

Please let me know what I need to do here, the BAM file I received has been sorted by coordinate, looks like it went through the ccs, pbtrim, and jasmine commands prior to my obtaining the files. I have a viable index, both in .bai and .pbi form. I'm not sure what could possibly be the issue, any advice would be greatly appreciated!

**Comment by ctsa** [comment]
Can you list the reference contigs from the input BAM file? For instance, the output from the following:

    samtools idxstats m84039_231121_213913_s2.hifi_reads.bam

**Comment by ctsa** [comment]
Hi @seetarajpara , I think you are right, the issue appears to be that these BAM files are unmapped.  The recommended read mapper for HiFiCNV is pbmm2. We can add an improved error message to HiFiCNV to clarify this case.

**Comment by seetarajpara** [comment]
thank you @ctsa for your prompt responses! I've been running the alignment and sorting, I think by that point I should be ready to run HiFiCNV and other downstream analyses. I appreciate your help!
