### ISSUE TITLE
No usable bins found for haploid depth estimation

### ISSUE THREAD

**Issue by aindap** [PacificBiosciences/HiFiCNV#30]
Hi HiFiCNV Team,

I'm testing out my Nextflow  pipeline on  subsetted chr20 BAM from [HG002 HiFi data](https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep1/analysis/) and getting the following error described below. 

Is this an artifact of the fact I am testing  aligned reads from a single chromosome? Or is there something else more fundamentally wrong with my experimental setup? 

Note, my input is a pbmm2 aligned BAM from chr20 reads from HG002 HiFi Revio data. 

Version: ```hificnv 1.0.0-36e6461```
Command:

```
hificnv --bam HG002.m84011_220902_175841_s1.GRCh38.chr20.unaligned.aligned.bam \
  --ref human_GRCh38_no_alt_analysis_set.fasta \
  --exclude  cnv.excluded_regions.common_50.hg38.bed.gz \
  --expected-cn expected_cn.hg38.XY.bed \
  --threads 32
```

Command error:

```
[2024-10-17][03:47:58][hificnv][ERROR] No usable bins found for haploid depth estimation. At least one depth bin with non-zero sequencing coverage is required outside of any excluded regions.
```

**Comment by holtjma** [comment]
Hi @aindap,

Were you able to resolve this on your end?

Matt

**Comment by aindap** [comment]
I think I had supplied an empty bam file by accident. Hence the error. Thanks for checking in.
