### ISSUE TITLE
which aligner is recommended? 

### ISSUE THREAD

**Issue by AhmedArslan** [PacificBiosciences/HiFiCNV#6]
I have a sorted alignment file (bam) with minimap2:
minimap2 -ax map-hifi -MD GRCh38.fa sample.fastq.gz > sample.sam
samtools view -b sample.sam | samtools sort -@ 7 -T ./tmp/{} -o sample.sorted.bam
 
For HiFICNV I am using the following command:
hificnv --bam sample.sorted.bam --ref GRCh38.fa --threads 15 --output-prefix sample.cnv --exclude cnv.excluded_regions.hg38.bed.gz --maf sample.deepvariant.vcf --expected-cn male_expected_cn.hg38.bed

[2023-03-29][06:03:51][hificnv][INFO] Starting hificnv [2023-03-29][06:03:51][hificnv][INFO] cmdline: 
hificnv --bam sample.sorted.bam --ref GRCh38.fa --threads 15 --output-prefix sample.cnv --exclude cnv.excluded_regions.hg38.bed.gz --maf sample.deepvariant.vcf --expected-cn male_expected_cn.hg38.bed [2023-03-29][06:03:51][hificnv][INFO] Running on 15 threads [2023-03-29][06:03:51][hificnv][INFO] Reading reference genome from file '/home/aarslan/data/reference/GRCh38/GRCh38_latest_genomic.primary.2.fa' [2023-03-29][06:03:57][hificnv][INFO] Reading excluded regions from file '/mnt/qnap/aarslan/tools/hificnv-v0.1.3-x86_64-unknown-linux-gnu/cnv.excluded_regions.hg38.bed.gz'
[2023-03-29][06:03:57][hificnv][INFO] Processing alignment file 'sample.sorted.bam'
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:', 17
/usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'Method assumes alignment CIGAR strings use seq match/mismatch (=/X) instead of alignment match (M)', /usr/local/cargo/git/checkouts/rust-vc-utils-bd4e9cc518074f37/ff04dbb/src/bam_utils.rs:58:17
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/bam_scanner.rs:72:63
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/bam_scanner.rs:72thread ':thread '<unnamed><unnamed>' panicked at '' panicked at '63called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }', thread '
thread '', src/bam_scanner.rs<unnamed>thread 'src/bam_scanner.rs<unnamed>' panicked at 'thread ':<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>72' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', ' panicked at ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }:63', src/bam_scanner.rsthread '', <unnamed>72
src/bam_scanner.rs:thread 'src/bam_scanner.rs' panicked at '::72<unnamed>:called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '6372:' panicked at '72', <unnamed>
:63called `Result::unwrap()` on an `Err` value: PoisonError { .. }:src/bam_scanner.rs' panicked at '63
', 63thread ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }
src/bam_scanner.rs
<unnamed>72', thread ':' panicked at ':src/bam_scanner.rs<unnamed>72called `Result::unwrap()` on an `Err` value: PoisonError { .. }63thread '' panicked at ':<unnamed>', 
called `Result::unwrap()` on an `Err` value: PoisonError { .. }:63' panicked at 'src/bam_scanner.rsthread 'thread 'thread '<unnamed>:thread '<unnamed><unnamed><unnamed>' panicked at '', ' panicked at '72' panicked at ':src/bam_scanner.rsthread 'thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }', 63src/bam_scanner.rs:<unnamed><unnamed>', called `Result::unwrap()` on an `Err` value: PoisonError { .. }', 
:72' panicked at '' panicked at 'src/bam_scanner.rs', src/bam_scanner.rs72:called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }:src/bam_scanner.rsthread '::63', ', 72:<unnamed>7263
src/bam_scanner.rssrc/bam_scanner.rs:7263' panicked at ':
:::
called `Result::unwrap()` on an `Err` value: PoisonError { .. }63', thread '727263
src/bam_scanner.rsthread '<unnamed>thread '' panicked at '::
:<unnamed><unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }63', 
thread '6372' panicked at '' panicked at 'src/bam_scanner.rs<unnamed>:
thread ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '' panicked at '72<unnamed>63', thread '', <unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }:' panicked at '
src/bam_scanner.rs<unnamed>src/bam_scanner.rs' panicked at '', thread '63called `Result::unwrap()` on an `Err` value: PoisonError { .. }:' panicked at ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs<unnamed>:
', 72called `Result::unwrap()` on an `Err` value: PoisonError { .. }72', ' panicked at '72src/bam_scanner.rs:', thread ':src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }::63src/bam_scanner.rs
<unnamed>63:', 6372thread ':' panicked at '
72src/bam_scanner.rs
:<unnamed>72called `Result::unwrap()` on an `Err` value: PoisonError { .. }::thread '63' panicked at ':', thread '6372<unnamed>
' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }63src/bam_scanner.rs<unnamed>thread ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }', 
:' panicked at '<unnamed>63', src/bam_scanner.rs72:called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '
thread 'src/bam_scanner.rs:72', called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>:63thread ':src/bam_scanner.rs', ' panicked at '72
<unnamed>63:src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }:' panicked at '
72thread ':', 63called `Result::unwrap()` on an `Err` value: PoisonError { .. }:', <unnamed>72thread 'src/bam_scanner.rs
63src/bam_scanner.rs' panicked at ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>:
:63', thread '' panicked at '7272
src/bam_scanner.rs<unnamed>:called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread 'thread '<unnamed>::63' panicked at '72', <unnamed>' panicked at '63
called `Result::unwrap()` on an `Err` value: PoisonError { .. }:src/bam_scanner.rs' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }
', 63:called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '', src/bam_scanner.rs
72thread ':', <unnamed>src/bam_scanner.rs:<unnamed>63src/bam_scanner.rsthread '' panicked at ':72' panicked at '
:<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }72:called `Result::unwrap()` on an `Err` value: PoisonError { .. }72' panicked at '', called `Result::unwrap()` on an `Err` value: PoisonError { .. }:thread '63', :src/bam_scanner.rssrc/bam_scanner.rs', 63<unnamed>
' panicked at '
63::src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }
', 7272::7263:src/bam_scanner.rs::
63thread '6372
thread '<unnamed>
:thread '<unnamed>' panicked at '63thread '<unnamed>' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }
<unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>', called `Result::unwrap()` on an `Err` value: PoisonError { .. }', ', src/bam_scanner.rs', thread '' panicked at 'src/bam_scanner.rssrc/bam_scanner.rs::72src/bam_scanner.rs<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }:72::' panicked at '', called `Result::unwrap()` on an `Err` value: PoisonError { .. }72:6372src/bam_scanner.rs:', :63
:63src/bam_scanner.rs63
thread '72
:
<unnamed>:thread '72' panicked at '63<unnamed>:called `Result::unwrap()` on an `Err` value: PoisonError { .. }
', ' panicked at 'thread 'thread '63src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed><unnamed>thread '
<unnamed>:', ' panicked at '' panicked at '' panicked at '72src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '', <unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }::src/bam_scanner.rs' panicked at '', ', thread '6372
::called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rssrc/bam_scanner.rs<unnamed>6372', ::' panicked at '
:src/bam_scanner.rsthread '7272called `Result::unwrap()` on an `Err` value: PoisonError { .. }63:
<unnamed>:thread ':', 72' panicked at '63<unnamed>thread '63src/bam_scanner.rs:called `Result::unwrap()` on an `Err` value: PoisonError { .. }
' panicked at '<unnamed>
:63', called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '72
src/bam_scanner.rsthread '', thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }::<unnamed>src/bam_scanner.rs<unnamed>thread '', 6372' panicked at ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }72', ' panicked at '<unnamed>src/bam_scanner.rs' panicked at ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }
::src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }72', 6363:', :src/bam_scanner.rs

thread '72src/bam_scanner.rs63:
<unnamed>::7272:thread '' panicked at '63:6363<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }

' panicked at 'thread '<unnamed>' panicked at 'thread ':thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '', 72<unnamed><unnamed>' panicked at '' panicked at 'thread 'src/bam_scanner.rs:called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>:6372
', ', src/bam_scanner.rs' panicked at '
:src/bam_scanner.rs:called `Result::unwrap()` on an `Err` value: PoisonError { .. }63:72', 
72:src/bam_scanner.rsthread ':thread ':63<unnamed>72<unnamed>63
' panicked at ':' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread '', called `Result::unwrap()` on an `Err` value: PoisonError { .. }63thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>src/bam_scanner.rsthread '72
<unnamed>thread '', ' panicked at '::' panicked at 'thread '<unnamed><unnamed>src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }:', thread '7263called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '72src/bam_scanner.rs<unnamed>:
', called `Result::unwrap()` on an `Err` value: PoisonError { .. }::' panicked at '63called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs', 6372
', :thread 'src/bam_scanner.rs
:src/bam_scanner.rs72<unnamed>:6372::' panicked at '
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
:7263', 63src/bam_scanner.rsthread 'thread ':

:thread '<unnamed><unnamed>6372<unnamed>' panicked at '' panicked at '
:thread 'thread '' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }63<unnamed><unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }', ', 
' panicked at '' panicked at '', src/bam_scanner.rssrc/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread 'src/bam_scanner.rs::thread '', ', <unnamed>:7272<unnamed>src/bam_scanner.rssrc/bam_scanner.rs' panicked at '72::6363' panicked at '::called `Result::unwrap()` on an `Err` value: PoisonError { .. }:', 63

called `Result::unwrap()` on an `Err` value: PoisonError { .. }7272src/bam_scanner.rs
', :::src/bam_scanner.rs636372thread 'thread 'thread ':

:<unnamed><unnamed>' panicked at '<unnamed>7263:' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at 'thread 'thread '
63called `Result::unwrap()` on an `Err` value: PoisonError { .. }', called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed><unnamed>
', src/bam_scanner.rs', ' panicked at '' panicked at 'thread 'thread 'src/bam_scanner.rs:src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed><unnamed>:72:', ', ' panicked at '' panicked at '72', 72src/bam_scanner.rssrc/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }::63src/bam_scanner.rs::', ', 63
:7272::src/bam_scanner.rssrc/bam_scanner.rs
726363:thread '::72

thread '72<unnamed><unnamed>63' panicked at '
::' panicked at '63called `Result::unwrap()` on an `Err` value: PoisonError { .. }63thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }
', 
<unnamed>', src/bam_scanner.rsthread '' panicked at 'src/bam_scanner.rs:<unnamed>thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }:72' panicked at '<unnamed>thread '', 72:called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '' panicked at '<unnamed>src/bam_scanner.rs:63', <unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at ':63
src/bam_scanner.rs' panicked at '', called `Result::unwrap()` on an `Err` value: PoisonError { .. }72
:called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs', :thread '72', :src/bam_scanner.rsthread '63<unnamed>
:src/bam_scanner.rs72:<unnamed>' panicked at '63::72thread '' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }
7263:<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }', :
63' panicked at 'thread '', src/bam_scanner.rs63
called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>src/bam_scanner.rs:
72', ' panicked at '::thread 'src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }72thread '63<unnamed>:', :<unnamed>
thread '' panicked at '72src/bam_scanner.rs63thread '
' panicked at '<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }::<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '', 63thread '72' panicked at '', called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs
<unnamed>:called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs', :' panicked at '63', :src/bam_scanner.rsthread '72<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }
src/bam_scanner.rs72::' panicked at '', ::7263called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread 'src/bam_scanner.rs7263:
', <unnamed>::
63src/bam_scanner.rs' panicked at '7263thread '
:called `Result::unwrap()` on an `Err` value: PoisonError { .. }:thread '
<unnamed>72', 63<unnamed>thread '' panicked at ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs
' panicked at '<unnamed>thread '63', :called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '<unnamed>thread '
src/bam_scanner.rs72', called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs' panicked at '<unnamed>:' panicked at ':', thread ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }72called `Result::unwrap()` on an `Err` value: PoisonError { .. }63src/bam_scanner.rs<unnamed>72', :', 
:' panicked at ':src/bam_scanner.rs63:src/bam_scanner.rs72called `Result::unwrap()` on an `Err` value: PoisonError { .. }63thread '
72::', 
<unnamed>:' panicked at '7263src/bam_scanner.rsthread '63called `Result::unwrap()` on an `Err` value: PoisonError { .. }:thread '
:<unnamed>72
', 63<unnamed>' panicked at ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs
' panicked at 'thread '63thread '', :called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>
thread 'src/bam_scanner.rs72:', ' panicked at '<unnamed>:thread '72src/bam_scanner.rs:called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '', 63<unnamed>:' panicked at '7263called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs', :
called `Result::unwrap()` on an `Err` value: PoisonError { .. }:
src/bam_scanner.rs72', 63thread '::src/bam_scanner.rs
<unnamed>thread '7263:
' panicked at '<unnamed>thread ':72called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '<unnamed>thread '63:', called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '<unnamed>
63src/bam_scanner.rs', called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at '
:src/bam_scanner.rsthread '', called `Result::unwrap()` on an `Err` value: PoisonError { .. }72', :<unnamed>72thread 'src/bam_scanner.rs:src/bam_scanner.rs' panicked at ':<unnamed>:63:called `Result::unwrap()` on an `Err` value: PoisonError { .. }63' panicked at '72
72', 
called `Result::unwrap()` on an `Err` value: PoisonError { .. }::src/bam_scanner.rs', 6363:src/bam_scanner.rsthread '
thread '
72:<unnamed><unnamed>:72' panicked at '' panicked at '63thread ':called `Result::unwrap()` on an `Err` value: PoisonError { .. }called `Result::unwrap()` on an `Err` value: PoisonError { .. }
<unnamed>63', ', thread '' panicked at '
called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rssrc/bam_scanner.rsthread '<unnamed>', ::<unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs7272called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '', :::', <unnamed>src/bam_scanner.rs726363src/bam_scanner.rs' panicked at '::

:called `Result::unwrap()` on an `Err` value: PoisonError { .. }726372', called `Result::unwrap()` on an `Err` value: PoisonError { .. }:
:thread 'src/bam_scanner.rsthread '63<unnamed>', 63' panicked at ':thread '<unnamed><unnamed>', 
src/bam_scanner.rs
72<unnamed>' panicked at '' panicked at 'src/bam_scanner.rscalled `Result::unwrap()` on an `Err` value: PoisonError { .. }::' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread ':<unnamed>', 7263called `Result::unwrap()` on an `Err` value: PoisonError { .. }', thread '72' panicked at 'src/bam_scanner.rs:
', src/bam_scanner.rs<unnamed>:called `Result::unwrap()` on an `Err` value: PoisonError { .. }:63src/bam_scanner.rs:' panicked at '63', thread '72
:7272called `Result::unwrap()` on an `Err` value: PoisonError { .. }
src/bam_scanner.rs<unnamed>:::', :src/bam_scanner.rs' panicked at 'thread '636363

72:called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '<unnamed>
' panicked at 'thread ':72', <unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }thread '<unnamed>63:src/bam_scanner.rs' panicked at '', thread '<unnamed>' panicked at '
63:called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }
72', :' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', ', :src/bam_scanner.rs63:src/bam_scanner.rs72thread 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }<unnamed>src/bam_scanner.rs
:72::72<unnamed>', thread '' panicked at '72:63:' panicked at 'src/bam_scanner.rs<unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }:63
63called `Result::unwrap()` on an `Err` value: PoisonError { .. }:' panicked at '', called `Result::unwrap()` on an `Err` value: PoisonError { .. }63

', 72src/bam_scanner.rsthread '', 
src/bam_scanner.rs::<unnamed>src/bam_scanner.rs' panicked at ':6372:called `Result::unwrap()` on an `Err` value: PoisonError { .. }72
' panicked at ':72', :63called `Result::unwrap()` on an `Err` value: PoisonError { .. }:src/bam_scanner.rs63
', 63:

src/bam_scanner.rs72::7263:
63
:63
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', <unnamed>called `Result::unwrap()` on an `Err` value: PoisonError { .. }' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }src/bam_scanner.rs', :src/bam_scanner.rs72::', 7263src/bam_scanner.rs:
63:
72:63

Please let me know where is the problem?

**Comment by holtjma** [comment]
@AhmedArslan Thanks for reporting this, it appears to be related to the issues from #4 which are caused by the Cigar strings that minimap2 uses (specifically, the "M" type).  In general, we recommend using [pbmm2](https://github.com/PacificBiosciences/pbmm2) which uses the "=" and "X" Cigar characters and is typically better suited for HiFi datasets.  In the short term, aligning with pbmm2 is our recommended workaround.

We're currently working on a fix for the cigar string issue and will clarify the supported aligners in the upcoming release as well.

**Comment by AhmedArslan** [comment]
@ Holkjma thank you. Since I am doing other type of analyses as well with the same bam file produced with minimap2. It would be desirable to have HiFiCNV use the same aligner. If possible, please let me know the tentative time line for the next release?
