### ISSUE TITLE
Difference reference file errors

### ISSUE THREAD

**Issue by Gedofs** [PacificBiosciences/HiFiCNV#8]
This time I used the reference to make my  BAM(GCA_000001405.15_GRCh38_no_alt_analysis_set.fna), however there is a new issue...

[2023-04-04][17:01:23][hificnv][INFO] Starting hificnv
[2023-04-04][17:01:23][hificnv][INFO] cmdline: hificnv --bam /Datos/sample.0-0.bam --ref /Datos/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --exclude /Datos/cnv.excluded_regions.common_50.hg38.bed.gz --expected-cn /Datos/female_expected_cn.hg38.bed --threads 7 --output-prefix 001
[2023-04-04][17:01:23][hificnv][INFO] Running on 7 threads
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
[2023-04-04][17:01:23][hificnv][INFO] Reading reference genome from file '/Datos/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna'
[2023-04-04][17:02:07][hificnv][INFO] Reading excluded regions from file '/Datos/cnv.excluded_regions.common_50.hg38.bed.gz'
[2023-04-04][17:02:07][hificnv][INFO] Reading expected CN regions from file '/Datos/female_expected_cn.hg38.bed'
[2023-04-04][17:02:07][hificnv][INFO] Processing alignment file '/Datos/sample.0-0.bam'
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /Datos/sample.0-0.bam.bai
**thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/bam_scanner.rs:234:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**

It panicked at called option.

**Comment by holtjma** [comment]
@Gedofs 

Sorry for the poor error message, I've made a note to fix that.

Digging into the code though, it looks like this is caused when the program encounters a chromosome that was in the BAM file but is not in the loaded reference file.  I know you just changed your reference to match the aligned file, so this is a little odd.  Can you provide the BAM header (specifically just the contig list) and the reference fasta contigs so we can verify there isn't some unexpected mismatch in the contigs?  You should be able to get the list with these commands:

```
# for the bam file
samtools view -H {BAM_FILE} | grep "@SQ" > bam_contigs.txt
# for the reference fasta file
grep ">" {FASTA_FILE} > reference_contigs.txt
```

If you can run those and then upload the two .txt files here, I can check that they match.

**Comment by Gedofs** [comment]
thanks. Here are the files
[reference_contigs.txt](https://github.com/PacificBiosciences/HiFiCNV/files/11153217/reference_contigs.txt)
[bam_contigs.txt](https://github.com/PacificBiosciences/HiFiCNV/files/11153218/bam_contigs.txt)

**Comment by holtjma** [comment]
So if you look in those files, you can find a bunch of contigs that are in the BAM file (e.g. `chr1_KI270762v1_alt`) that are _not_ in the reference file.  HiFiCNV needs the same reference file that was used for alignment or it won't be able to correctly assess GC-content (hence the error).  If you can get the _exact_ same reference file used for alignment, then this issue should resolve.

We have a patch implemented on the error message to make this clearer in the future that will go into the next release.

**Comment by holtjma** [comment]
@Gedofs were you able to resolve this on your end?

**Comment by Gedofs** [comment]
Im working on it, i'll let you know later today

**Comment by Gedofs** [comment]
I was able to recover the* same reference file* that was used for the
alignment as you suggested.
Finally, I could run it successfully.

Many thanks,

Gerardo Fabián

[image: Screenshot 2023-04-11 at 12.48.11.png]
